nucleotide = 'GGCCTGGATATCTTTACGCAACTGACTACCTCGACTCAAGATGTAGCCAGACCGCTAAGATCTGTGGTAAGCTCAGAGTCCTTGTACACCTTACCCATCGGACACAGACCCGATATGCACATGCTCGAGTTTCGGCATCTAACCCCAGCGAATCTCTTAATAAGCGCTTCTCGGATCAGGGTTACCTAAGGCTATATGCATTCTATTGGCTGTGTCACCAGTGGACGAAACTAAGAGAACCGACACAGCCCCGAACACGCGGAATAGGGTGGCATTGGTCTATATGCTAGCATTTTGACCTCTATGGTGTGCATTCCTAGTGGTTACAATGCGCCCTTCCCGGCCCCACCGCAACATGGCCAACGGTACCCGCACGTTTACGTGCATTTGCCTGTGTCGGTGTTCCTCGATTGATCCGACAGTTTAATAACACATCAGTAGGGCGGTATACCGAAGCCCTGTTCTTTCCATAGATTCGGTCGCCGCGGGAAGCTTTGCTGCCAACTGAATGAGGGATGCCAATTCCGTACGCACAATGGATGTCCCGTATCGTTGAAGCGGCGGAGTGCTAGACCCGCAGTTCCTATTGCCAGAGTCTGGCCGGGCAATGGGAATCCTCGCTACGAGATGATAGTCTAAAGATTTCGACCCCCGTGTTGGCCCAAGCCCATCGGATGCCGAGTGAGTGCGATTTAGGCTACTTGAGACCGGTATGAATATGCTATTGAGTGGCATACGATACTTCGAATCGAGTGCAACGTGTATTGAAGCGCCCCGGCTCAGCTAACCCCGTAGTACAAT'
# My solution
i = 0
check = 'ACGT'
sum = ''
for j in range(0, 4):
    ind = 0
    for i in range(0, len(nucleotide)):
        if nucleotide[i] == check[j]:
            ind += 1
    sum = sum + str(ind) + " "
print
"1.", sum.strip()

# Seen solution
freq = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
for i in nucleotide:
    freq[i] = freq[i] + 1

print
"2.", freq['A'], freq['C'], freq['G'], freq['T']

# Another Solution
print
"3.", [nucleotide.count(c) for c in 'ACGT']

# 4th
a = nucleotide.count("A")
c = nucleotide.count("C")
g = nucleotide.count("G")
t = nucleotide.count("T")
print
"4.", a, c, g, t
